Phordle/Phordle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('user.urls')),
    path('image/', include('image_upload.urls')),
    path('theme/', include('theme.urls')),
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('feed/', include('feed.urls')),
    path('group/', include('group.urls')),
    path('about/', include('about.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Phordle/about/urls.py
from django.urls import path

from . import views

app_name = "about"
urlpatterns = [ path("", views.about, name='about')]

Phordle/feed/urls.py
from django.urls import path

from . import views

app_name = "feed"
urlpatterns = [ path("", views.FeedView.as_view(), name='feed')]

Phordle/group/urls.py
from django.urls import path

from . import views

app_name = "group"
urlpatterns = [ path("create_group/", views.create_group, name="create_group"),
                path("<int:pk>/group", views.group, name="group_info"),
                path("group_list/", views.GroupList.as_view(), name="group_list"),
                path("group_theme/", views.group_theme, name="group_theme") ]

Phordle/image_upload/urls.py
from django.urls import path

from . import views

app_name = "image_upload"
urlpatterns = [ path("", views.index, name="upload")]

Phordle/theme/urls.py
from django.urls import path

from . import views

app_name = "theme"
urlpatterns = [ path("quickstart/", views.Quickstart.as_view(), name="quickstart"),
                path("create_theme", views.create_theme, name="create_theme"),
                path("<int:pk>/", views.theme_view, name="theme")]

Phordle/templates/base.html
<!-- base.html -->
<!DOCTYPE html>
<html lang="en-us">
<head>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    <!-- Common meta tags, styles, etc. -->
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter&display=swap');
        :root {
            --bg-color: #121212;
            --primary-color: #252525;
            --secondary-color: #4c4c4c;
            --font-size: 20px;
            --font-family: 'Inter', sans-serif;
        }

        body {
            background-color: var(--bg-color);
            font-size: var(--font-size);
            padding: 0;
            margin: 0;
            height: 100vh;
        }

        .btn {
			margin-top: 1.25rem; /* 20px */
			background-color: var(--secondary-color);
			color: white;
			padding: 0.625rem 1.25rem; /* 10px 20px */
			border: none;
			border-radius: 0.3125rem; /* 5px */
			cursor: pointer;
		}

        .custom-navbar {
            background-color: var(--primary-color);     
        }

        .custom-navbar .navbar-brand {
            color: white;
        }

        .custom-navbar .nav-link {
            color: white;
        }

        li.nav-item {
            display: flex;
            align-items: center;
            justify-content: center;
            margin: 0rem 2rem 0rem 2rem;
        }

        h1, h2, h3, h4, h5, h6, label, p {
            color: white;
        }

        a {
            color: white;
        }

        @media screen and (max-width: 576px) {
			.card {
				max-width: 90%;
				height: auto;
				padding: 1rem;
			}
		}
		
		@media screen and (max-width: 768px), (max-height: 708px) {
			.card {
				max-width: 80%;
				height: auto;
				padding: 1.5rem;
			}
		}
		
		@media screen and (max-height: 500px) {
			.card {
				max-width: 25rem;
				height: 65vh;
				padding: 1.5rem;
			}
			.btn {
				margin-top: 1rem;
			}
		}
    </style>
<head>
<body>
    <nav class="navbar navbar-expand-lg custom-navbar fixed-top">
        <ul class="navbar-nav mr-auto">
            <li class='nav-item'>
                <a class="navbar-brand" href="{% url 'feed:feed' %}">
                    HOME
                </a>
            </li>
        
            {% if request.user.is_authenticated %}
                <li class='nav-item'>
                    <a class='nav-link' href="{% url 'logout' %}">Log Out</a>
                </li>
                <li class='nav-item'>
                    <a class='nav-link' href="{% url 'profile' %}">Profile</a>
                </li>
            {% else %}
                <li class='nav-item'>
                    <a class='nav-link' href="{% url 'login' %}">Log In</a>
                </li>
            {% endif %}
                <li class='nav-item'>
                    <a class='nav-link' href="{% url 'theme:quickstart' %}">Quickstart</a>
                </li>
                <li class='nav-item'>
                    <a class='nav-link' href="{% url 'group:group_list' %}">Groups</a>
                </li>
                <li class='nav-item'>
                    <a class='nav-link' href="{% url 'image_upload:upload' %}">Word tester</a>
                </li>
                <li class='nav-item'>
                    <a class='nav-link' href="{% url 'about:about' %}">About</a>
                </li>
        </ul>
    </nav>
    <!-- Common header, navigation, etc. -->
    
    {% block content %}
    {% endblock %}
    
    <!-- Common footer, scripts, etc. -->
</body>
</html>