Phordle/Phordle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('user.urls')),
    path('image/', include('image_upload.urls')),
    path('theme/', include('theme.urls')),
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('feed/', include('feed.urls')),
    path('group/', include('group.urls')),
    path('about/', include('about.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Phordle/feed/urls.py
from django.urls import path

from . import views

app_name = "feed"
urlpatterns = [ path("", views.FeedView.as_view(), name='feed')]

Phordle/group/urls.py
from django.urls import path

from . import views

app_name = "group"
urlpatterns = [ path("create_group/", views.create_group, name="create_group"),
                path("<int:pk>/group", views.group, name="group_info"),
                path("group_list/", views.GroupList.as_view(), name="group_list"),
                path("group_theme/", views.group_theme, name="group_theme") ]

Phordle/user/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.SignIn.as_view(), name='login'),
    path('logout/', views.sign_out, name='logout'),
    path('', views.sign_up, name='register'),
    path('profile/', views.Profile.as_view(), name='profile'),
    path('anon/', views.anon_sign_up, name='anon_sign_up'),
]

Phordle/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

Phordle/user/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

class RegisterForm(UserCreationForm):
    username = forms.CharField(label="Username:", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Enter username'}))
    email = forms.EmailField(label="Email:", widget=forms.EmailInput(attrs={'class':'form-control', 'placeholder':'Enter email'}))
    password1 = forms.CharField(label="Password:", widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'Enter password'}))
    password2 = forms.CharField(label="Confirm Password:", widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'Confirm password'}))
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

Phordle/user/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout, get_user_model
from django.contrib.auth.views import LoginView
from django.http import HttpResponse
from django.views import generic
from django.utils import timezone
from django.contrib.auth.models import User

from feed.models import Image
from group.models import Group

################ random name for anon generator
import random
import string

def get_random_string(length):
    # choose from all lowercase letter
    letters = string.ascii_lowercase
    result_str = ''.join(random.choice(letters) for i in range(length))
    return result_str
################

def anon_sign_up(request):
    s = get_random_string(10)
    username = f"anon{s}"
    password = f"anon{s}"
    email = f"anon{s}"

    user = User.objects.create_user(username=username, password=password, email=email)
    user.save()
    login(request, user)
    return redirect('theme:quickstart')

def sign_up(request):
    if request.method == 'GET':
        form = RegisterForm()
        return render(request, 'user/register.html', { 'form': form}) 
    elif request.method == 'POST':
        form = RegisterForm(request.POST) 
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            messages.success(request, 'You have singed up successfully.')
            login(request, user)
            return redirect('feed:feed')
        else:
            return render(request, 'user/register.html', {'form': form})

class SignIn(LoginView):
    template_name = 'user/login.html'
    next_page = 'theme:quickstart'

def sign_out(request):
    logout(request)
    messages.success(request, "You have logged out successfully.")
    return redirect('feed:feed')

class Profile(generic.ListView):
    template_name = 'user/profile.html'
    context_object_name = 'user_profile_groups'

    def get_queryset(self):
        return Group.objects.filter(users=self.request.user.id).all()

def sign_in_anon(request):
    return redirect('image_upload')
        

Phordle/user/templates/user/login.html
{% extends 'base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en-us">
<head>
	<style>
		body {
			margin: 0;
			padding: 0;
			background-color: var(--bg-color);
			font-size: var(--font-size);
			font-family: var(--font-family);
			overflow: hidden;
		}

		.card {
			background-color: var(--primary-color);
			border-radius: 1rem;
			width: 100%;
			max-width: 40rem; /* Adjust this as needed for larger screens */
			padding: 2rem;
			text-align: center;
			border: solid .5rem var(--secondary-color);
		}

		.wrapper {
			display: flex;
			align-items: center;
			justify-content: center;
			min-height: calc(100vh - 6.25rem); /* Adjust for navbar */
		}

		.form {
			margin: 0;
			color: white;
			display: flex;
			flex-direction: column;
			align-items: center;
			justify-content: space-between; /* Adjust to push content to top */
			height: 100%; /* Ensure the form container takes full height */
		}

		label {
			color: white;
		}

		p {
			color: white;
			margin: 10px;
			text-align: left;
		}

		h2 {
			color: white;
		}

		li {
			color: white;
		}
		
		input[type="text"],
		input[type="text"]:focus,
		input[type="password"],
		input[type="password"]:focus {
			width: 100%;
			padding: 0.5rem; /* 8px */
			border-radius: 0.3125rem; /* 5px */
			background-color: var(--secondary-color);
			color: white;
		}

		input[type="text"]::placeholder,
		input[type="password"]::placeholder {
			color: var(--bs-gray-200);
		}

		.btn {
			margin-top: 1.25rem; /* 20px */
			background-color: var(--secondary-color);
			color: white;
			padding: 0.625rem 1.25rem; /* 10px 20px */
			border: none;
			border-radius: 0.3125rem; /* 5px */
			cursor: pointer;
		}
	</style>
	<title>Log In</title>
</head>
<body>
	<div class="wrapper">
		<div class="card">
			<form method="POST" novalidate>
				{% csrf_token %}
				<h2>Log In</h2>
				{{form.as_p}}
				<input class="btn" type="submit" value="Login" />
				<p class="text-center">Don't have an account? <a href="{%url 'register' %}">Register</a></p>
			</form>
		</div>
	</div>
</body>
{% endblock content %}

Phordle/user/templates/user/profile.html
{% extends 'base.html' %}

{% block content %}
    <head>
        <style>
            body {
                display: flex;
                justify-content: center;
                align-items: center;
                height: 100vh;
                flex-direction: column;
            }

            .container {
                display: flex;
                flex-direction: column;
                justify-content: center;
                align-items: center;
                background-color: var(--primary-color);
                border-radius: 1rem;
                border: solid .5rem var(--secondary-color);
                padding: 2rem;
                max-width: 600px;
            }
        </style>
    </head>
    <body>
        <div class="container">
            {% if request.user.is_authenticated %}
                <h1>Hello {{request.user.get_username }}</h1>
                {% if user_profile_images %}
                    <ul>
                        {% for image in user_profile_images %}
                            
                        <img alt="" src="{{ image.image.url }}">
                            
                        {% endfor %}
                    </ul>
                {% else %}
                    <p> You haven't posted any images yet. </p>
                {% endif %}
                {% if user_profile_groups %}
                    <p>Groups:</p>
                    {% for group in user_profile_groups %}
                        <a href="{% url 'group:group_info' group.id %}">{{ group.name }}:Add User</a>
                    {% endfor %}
                {% else %}
                    <p>Not in any groups</p>
                {% endif %}
                <a href="{%url 'group:create_group' %}">Create Group</a>
            {% else %}
                <p>Not logged in</p>
            {% endif %}
        </div>
    </body>
{% endblock content %}

Phordle/user/templates/user/register.html
{% extends 'base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en-us">
<head>
	<style>
		body {
			margin: 0;
			padding: 0;
			background-color: var(--bg-color);
			font-size: var(--font-size);
			font-family: var(--font-family);
			overflow: hidden;
		}
		.wrapper {
			display: flex;
			align-items: center;
			justify-content: center;
			min-height: calc(100vh - 6.25rem); /* Adjust for navbar */
		}
		.form {
			margin: 0;
			color: white;
			display: flex;
			flex-direction: column;
			align-items: center;
			justify-content: space-between; /* Adjust to push content to top */
			height: 100%; /* Ensure the form container takes full height */
		}
		p {
			margin: 10px;
			text-align: left;
			min-width: 20vw;
		}
		.card {
			background-color: var(--primary-color);
			border-radius: 1rem;
			width: 100%;
			max-width: 40rem; /* Adjust this as needed for larger screens */
			height: 65vh; /* Set the card's height to 50% of the viewport height */
			padding: 2rem;
			text-align: center;
			border: solid .5rem var(--secondary-color);
		}

		.anonymous {
			color: white;
			text-decoration: none;
		}

		.anonymous:hover {
			text-decoration: underline;
		}
		
		
		input[type="text"],
		input[type="text"]:focus,
		input[type="email"],
		input[type="email"]:focus,
		input[type="password"],
		input[type="password"]:focus {
			width: 100%;
			padding: 0.5rem; /* 8px */
			border-radius: 0.3125rem; /* 5px */
			background-color: var(--secondary-color);
			color: white;
		}

		input[type="text"]::placeholder,
		input[type="password"]::placeholder
		input[type="email"]::placeholder {
			color: var(--bs-gray-200);
		}
	</style>
	<title>Register</title>
</head>
<body>
	<div class="wrapper">
		<div class="card">
			<form class="form" method="POST" novalidate>
				{% csrf_token %}
				<h2 class="text-center">Sign Up</h2>
				{{ form.as_p }}
				<input class="btn" type="submit" value="Register">
				<br>
				<a class="anonymous" href="{%url 'anon_sign_up' %}">Anonymous account</a>
			</form>
		</div>
	</div>
</body>


{% endblock content%}