Phordle/Phordle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('user.urls')),
    path('image/', include('image_upload.urls')),
    path('theme/', include('theme.urls')),
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('feed/', include('feed.urls')),
    path('group/', include('group.urls')),
    path('about/', include('about.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Phordle/feed/urls.py
from django.urls import path

from . import views

app_name = "feed"
urlpatterns = [ path("", views.FeedView.as_view(), name='feed')]

Phordle/group/urls.py
from django.urls import path

from . import views

app_name = "group"
urlpatterns = [ path("create_group/", views.create_group, name="create_group"),
                path("<int:pk>/group", views.group, name="group_info"),
                path("group_list/", views.GroupList.as_view(), name="group_list"),
                path("group_theme/", views.group_theme, name="group_theme") ]

Phordle/theme/urls.py
from django.urls import path

from . import views

app_name = "theme"
urlpatterns = [ path("quickstart/", views.Quickstart.as_view(), name="quickstart"),
                path("create_theme", views.create_theme, name="create_theme"),
                path("<int:pk>/", views.theme_view, name="theme")]

Phordle/group/models.py
from django.db import models
from theme.models import Theme
from django.conf import settings

class Group(models.Model):
    name = models.CharField(max_length=25, default="")
    theme = models.OneToOneField(Theme, on_delete=models.CASCADE)
    users = models.ManyToManyField(settings.AUTH_USER_MODEL)

Phordle/group/forms.py
from django import forms

from .models import Group

class GroupForm(forms.ModelForm):

    class Meta:
        model = Group
        fields = ["name"]

class AddUserForm(forms.ModelForm):
    add_user = forms.CharField()

    class Meta:
        model = Group
        fields = []

Phordle/group/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic 
from django.contrib.auth.models import User

from django.forms.formsets import formset_factory

from .forms import GroupForm, AddUserForm
from theme.forms import ThemeForm
from group.models import Group

def create_group(request):
    GroupFormSet = formset_factory(GroupForm)

    if request.method == 'GET':
        form = ThemeForm()
        formset = GroupFormSet()

        return render(request, 'group/create_group.html', {'form': form, 'formset': formset}) 
    elif request.method == 'POST':
        form = ThemeForm(request.POST)
        formset = GroupFormSet(request.POST)
        if all([form.is_valid(), formset.is_valid()]):
            theme = form.save()
            for inline_form in formset:
                if inline_form.cleaned_data:
                    group = inline_form.save(commit=False)
                    group.theme = theme
                    group.save()
                    group.users.set([request.user.pk])
            return redirect('profile')
        else:
            return render(request, 'group/create_group.html', {'form': form})

def group(request, pk):
    group = Group.objects.get(pk=pk)

    if request.method == 'GET':
        form = AddUserForm()

        return render(request, 'group/detail.html', {'form': form, 'group': group})
    elif request.method == 'POST':
        result_form = AddUserForm(request.POST)
        form = AddUserForm()
        try:
            user = User.objects.filter(username=result_form.data['add_user'])[0]
        except IndexError:
            return render(request, 'group/detail.html', {'form':form, 'group': group, 'err':True})

        group.users.set([user.pk])

        form = AddUserForm()

        return render(request, 'group/detail.html', {'form': form, 'group': group})


class GroupList(generic.ListView):
    template_name = 'user/group_list.html'
    context_object_name = 'user_groups'

    def get_queryset(self):
        return Group.objects.filter(users=self.request.user.id).all()

def group_theme(request, pk):
    theme = Group.objects.get(pk=pk).theme

    return render(request, 'group/group_theme', {})

Phordle/group/templates/group/create_group.html
{% extends 'base.html' %}
{% block content %}
<head>
    <style>
    body {
        height: 100vh;
        display: flex;
        justify-content: center;
        align-items: center;
    }    
    .container {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        background-color: var(--primary-color);
        border-radius: 1rem;
        border: solid .5rem var(--secondary-color);
        padding: 2rem;
        max-width: 600px;
        height: 100%;

    }

    .container form {
        width: 100%;
        max-width: 400px;
    }

    input, .form-control {
        background-color: var(--secondary-color);
        border-radius: 0.25rem;
    }

    table {
        margin: 0;
    }
    </style>
</head>
<body>
    <form method="post">
        <div class="container">
            {% csrf_token %}

            <table>
                {{ form }}
                {{ formset }}
            </table>
            <button class="btn" type="submit">Submit</button>
        </div>
    </form>
</body>
{% endblock %}

Phordle/group/templates/group/detail.html
{% extends 'base.html' %}

{% block content %}
<head>
    <style>
    body {
        height: 100vh;
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
    }
    </style>
</head>
<body>
    <h1 style="margin-bottom: 1rem;">{{ group.name }}</h1>
    <form method="post">
        {% csrf_token %}    
        {{ form }}
        <button type="submit">Add User</button>
        {% if err %}
            <p> User not found </p>
        {% endif %}
    </form>
</body>
{% endblock %}

Phordle/group/templates/group/group_list.html
{% extends 'base.html' %}

{% block content %}
<head>
    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            flex-direction: column;
        }

        .container {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            background-color: var(--primary-color);
            border-radius: 1rem;
            border: solid .5rem var(--secondary-color);
            padding: 2rem;
            max-width: 600px;
        }
    </style>
</head>
<div class="container">
    {% if user_groups %}
        <h1 style="margin-bottom: 1rem;">Groups</h1>
        {% for group in user_groups %}
            <a href="{% url 'theme:theme' group.theme.id %}">{{ group.name }}</a>
        {% endfor %}
    {% else %}
        <p>Not in any groups</p>
    {% endif %}
    <a href="{%url 'group:create_group' %}">Create Group</a>
</div>
{% endblock %}